<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\ToolsBox.Core\ToolsBox.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Diagnostics.Tracing.TraceEvent" Version="3.1.21" />
    <PackageReference Include="SharpSevenZip" Version="2.0.128" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets\7z.dll" LogicalName="ToolsBox.ArchiveRecovery.7z.dll" />
    <EmbeddedResource Include="Assets\*-LICENSE.txt" />
    <EmbeddedResource Include="Assets\ArchiveEngine-NOTICE.md" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ToolsBox.Windows.Tests" />
    <InternalsVisibleTo Include="ToolsBox.App.Tests" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
